### ISSUE TITLE
Make bootstrap a parallel process

### ISSUE THREAD

**Issue by juchiyu** [juchiyu/PTCA4CATA#1]

**Comment by mychan24** [comment]
Used `foreach` to implement parallel processing of bootstrap. By default, it will use n-1 core (7 cores on an 8-core computer), may add parameter to change that in the future. 

While running on multiple core reduces the overall time, the reduction in time is not linear. As more cores running slows the process of each core. 
For example, running something that takes 100s in a sequential for loop takes ~40s in a 7-core parallelize process.

**Comment by mychan24** [comment]
Don't close until @juchiyu check on Windows computer and Mic check on Linux server
